### ISSUE TITLE
Can't parse any of the test files

### ISSUE THREAD

**Issue by nivv** [byrokrat/autogiro#9]
I've been looking for a way to parse BGC-files and found this package. However none of the test files work. When trying the new format this is the error I get

```php
[byrokrat\autogiro\Exception\ContentException] Tree invalid due to the following issues:
Parser: Syntax error, expecting '01', REQ_OPENING_RECORD, REQ_MANDATE_LAYOUT, REQ_PAYMENT_LAYOUT, REQ_AMENDMENT_LAYOUT, REQUEST_FILE, '01', RESP_MANDATE_OPENING_OLD_RECORD, '01', GENERIC_OPENING_RECORD, RESP_MANDATE_FILE, FILE on line 1
```

If I remove the following from the test file:

```
[---+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
```

I get below error instead

```php
[byrokrat\autogiro\Exception\ContentException] Tree invalid due to the following issues:
Parser: Syntax error, expecting ALPHA-NUMERIC on line 1
```

**Steps to reproduce**

1. Download zip

2. Add a testfile

3. 

```php
<?php
require_once('vendor/autoload.php');
$factory = new \byrokrat\autogiro\Parser\ParserFactory;
$parser = $factory->createParser();
$fileNode = $parser->parse(file_get_contents('tests/ny_layout/autogiro_exempelfil_bet-spec-o-tk_sv.txt'));

```

**Comment by hanneskod** [comment]
Yupp, the files under `tests` don't parse. This is still work in progress. Autogirot contains many diffrent file layouts, at the moment this package can parse mandate requests and reponses and transaction requests. These tests can be found in the `features` dir and are executed with [behat](http://behat.org).

The testfiles under `tests` are downloaded from bgc.se and will be moved to proper feature tests as more layouts are supported.

The current timeframe is to add support for all major layouts during this winter...

Is there a layout you are specifically interested in?

**Comment by hanneskod** [comment]
Closing as there has been no development...
